Update patch set 1
Patch Set 1:

(2 comments)

Naming is inconsistent in the array names, causing build to fail.

Also, 

        if (preference == mCheckBox) {
                          ^
  symbol:   variable mCheckBox
  location: class NfcEnabler
packages/apps/Settings/src/com/android/settings/nfc/NfcEnabler.java:106: error: cannot find symbol
            final int desiredPolling = (Int) value;

                                        ^
  symbol:   class Int
  location: class NfcEnabler
packages/apps/Settings/src/com/android/settings/nfc/NfcEnabler.java:107: error: cannot find symbol
            Settings.System.putInt(resolver, Settings.System.RADIO_NFC_POLLING,
                                   ^
  symbol:   variable resolver
  location: class NfcEnabler
packages/apps/Settings/src/com/android/settings/nfc/NfcEnabler.java:107: error: package Settings does not exist
            Settings.System.putInt(resolver, Settings.System.RADIO_NFC_POLLING,
                                                     ^
packages/apps/Settings/src/com/android/settings/nfc/NfcEnabler.java:107: error: package Settings does not exist
            Settings.System.putInt(resolver, Settings.System.RADIO_NFC_POLLING,
                    ^
packages/apps/Settings/src/com/android/settings/WirelessSettings.java:272: error: cannot find symbol
        ListPreference polling = (ListPreference) findPreference(KEY_NFC_POLLING);
        ^
  symbol:   class ListPreference
  location: class WirelessSettings
packages/apps/Settings/src/com/android/settings/WirelessSettings.java:272: error: cannot find symbol
        ListPreference polling = (ListPreference) findPreference(KEY_NFC_POLLING);

Patch-set: 1
Reviewer: Gerrit User 1000000 <1000000@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=0