Update patch set 1
Patch Set 1: Code-Review+1

ERROR: resource directory 'packages/apps/OmniGears/res' does not exist make: *** [/home/erikcas/jenkins/workspace/OMNICM/android-5.0/out/target/common/obj/APPS/Settings_intermediates/src/R.stamp] Error 1 make: *** Waiting for unfinished jobs....

Max, this needs to be merged or we have to think of another solution. Build is currently broken. And yes I have synced omnigears

Patch-set: 1