Update patch set 2
Patch Set 2: Code-Review-1

Build fails:
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBarWindowManager.java:59: error: no suitable method found for getIntForUser(ContentResolver,String,int,UserHandle)
        boolean enableLockScreenRotation = Settings.System.getIntForUser(mContext.getContentResolver(),
                                                          ^
    method System.getIntForUser(ContentResolver,String,int) is not applicable
      (actual and formal argument lists differ in length)
    method System.getIntForUser(ContentResolver,String,int,int) is not applicable
      (actual argument UserHandle cannot be converted to int by method invocation conversion)
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBarWindowManager.java:61: error: no suitable method found for getIntForUser(ContentResolver,String,int,UserHandle)
        boolean enableAccelerometerRotation = Settings.System.getIntForUser(mContext.getContentResolver(),
                                                             ^
    method System.getIntForUser(ContentResolver,String,int) is not applicable
      (actual and formal argument lists differ in length)
    method System.getIntForUser(ContentResolver,String,int,int) is not applicable
      (actual argument UserHandle cannot be converted to int by method invocation conversion)

Patch-set: 2
Reviewer: Gerrit User 1000049 <1000049@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=-1