Update patch set 4
Patch Set 4:

Yanuar could not get it to build, even with the change you mentioned on line 310.
packages/apps/Settings/src/com/android/settings/wifi/AdvancedWifiSettings.java:194: error: cannot find symbol
            String value = mWifiManager.getCountryCode();
                                       ^
  symbol:   method getCountryCode()
  location: variable mWifiManager of type WifiManager
packages/apps/Settings/src/com/android/settings/wifi/AdvancedWifiSettings.java:197: error: method updateChannelSummary in class AdvancedWifiSettings cannot be applied to given types;
                updateChannelSummary(ccodePref, value);
                ^
  required: Preference,int
  found: ListPreference,String
  reason: actual argument String cannot be converted to int by method invocation conversion
packages/apps/Settings/src/com/android/settings/wifi/AdvancedWifiSettings.java:310: error: method updateChannelSummary in class AdvancedWifiSettings cannot be applied to given types;
                updateChannelSummary(preference, value);
                ^
  required: Preference,int
  found: Preference,String
  reason: actual argument String cannot be converted to int by method invocation conversion

Perhaps i missed something

Patch-set: 4
Label: Code-Review=0